apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  config.yaml: |
    multitenancy_enabled: true
    tenant_federation:
      enabled: true

    blocks_storage:
      backend: filesystem
      bucket_store:
        sync_dir: /tmp/mimir/tsdb-sync
      filesystem:
        dir: /tmp/mimir/data/tsdb
      tsdb:
        dir: /tmp/mimir/tsdb

    alertmanager:
      data_dir: /tmp/mimir/alertmanager
      enable_api: true
      fallback_config_file: /tmp/mimir/alertmanager-config/alertmanager-fallback-config.yaml

    alertmanager_storage:
      backend: filesystem
      filesystem:
        dir: /tmp/mimir/alert-store

    compactor:
      data_dir: /tmp/mimir/compactor
      sharding_ring:
        kvstore:
          store: memberlist

    distributor:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist

    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
        replication_factor: 1

    ruler:
      alertmanager_url: http://mimir:9009/alertmanager
      enable_api: true
      rule_path: /tmp/mimir/ruler
      tenant_federation:
        enabled: true

    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /tmp/mimir/rules

    server:
      http_listen_port: 9009
      log_level: info

    store_gateway:
      sharding_ring:
        replication_factor: 1
