apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:latest
          args: [
            "-config.file=/etc/mimir/config.yaml",
            "-target=all,alertmanager",
          ]
          ports:
            - containerPort: 9009
          volumeMounts:
            - name: config-volume
              mountPath: /etc/mimir
            - name: alertmanagerconfig-volume
              mountPath: /tmp/mimir/alertmanager-config/
      volumes:
        - name: config-volume
          configMap:
            name: mimir-config
        - name: alertmanagerconfig-volume
          configMap:
            name: mimir-alertmanager-config
