package helpers

import (
	"context"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	openslov1 "github.com/oskoperator/osko/api/openslo/v1"
	"github.com/oskoperator/osko/internal/config"
	"github.com/oskoperator/osko/internal/errors"
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	"github.com/prometheus/common/model"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	ctrllog "sigs.k8s.io/controller-runtime/pkg/log"
)

const (
	RecordPrefix = "osko"

	gaugeAggregation   = "avg_over_time"
	counterAggregation = "rate"

	annotationGroupBy            = "osko.dev/groupBy"
	annotationLongWindowStrategy = "osko.dev/longWindowStrategy"
	annotationMagicAlerting      = "osko.dev/magicAlerting"
	annotationAlertingTool       = "osko.dev/alertingTool"
	annotationBaseWindow         = "osko.dev/baseWindow"

	// longWindowStrategyDerived computes long-window SLI measurements by
	// averaging the base-window osko_sli_measurement recording rule instead of
	// re-scanning the raw source series over the long range.
	longWindowStrategyDerived = "derived"
	// longWindowStrategyRaw computes every window straight from the raw source
	// series. Correct, but dramatically more expensive on long windows.
	longWindowStrategyRaw = "raw"

	budgetingMethodOccurrences = "Occurrences"

	defaultReportingWindow = "28d"

	// maxRawWindow is the longest range we are willing to evaluate directly
	// against raw source series. Anything longer is derived from the base
	// window measurement when the derived strategy is active.
	maxRawWindow = model.Duration(6 * time.Hour)

	// LabelManagedBy marks resources generated by OSKO. A ThanosRuler
	// ruleSelector can match on it to discover generated PrometheusRule
	// objects, because a null label selector matches no objects.
	LabelManagedBy = "app.kubernetes.io/managed-by"

	// LabelManagedByValue is the value LabelManagedBy is set to.
	LabelManagedByValue = "osko"

	// LabelSLOName records which SLO a generated resource belongs to.
	LabelSLOName = "osko.dev/slo"
)

// alertingWindows are the fixed short/long window pairs used by the
// multi-burn-rate alerts. They are always recorded so the alerts can reference
// them regardless of the configured base and reporting windows.
var alertingWindows = []string{"5m", "30m", "1h", "2h", "6h", "24h", "3d"}

type MonitoringRuleSet struct {
	Slo        *openslov1.SLO
	Sli        *openslov1.SLI
	TargetRule monitoringv1.Rule
	BaseRule   monitoringv1.Rule
	GoodRule   monitoringv1.Rule
	TotalRule  monitoringv1.Rule
	BaseWindow string
}

// window couples a window's literal spelling (used verbatim in PromQL and in
// the `window` label) with its parsed duration (used for ordering and for the
// raw/derived split).
type window struct {
	name     string
	duration model.Duration
}

func mapToColonSeparatedString(labels map[string]string) string {
	log := ctrllog.FromContext(context.Background())

	pattern := "__.*?__"
	re, err := regexp.Compile(pattern)
	if err != nil {
		log.Error(err, "Failed to compile regex pattern")
	}

	keys := make([]string, 0, len(labels))
	for k := range labels {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	pairs := make([]string, 0, len(labels))
	for _, k := range keys {
		if re.MatchString(k) {
			continue
		}
		pairs = append(pairs, fmt.Sprintf("%s=\"%s\"", k, labels[k]))
	}

	return strings.Join(pairs, ", ")
}

func mergeLabels(ms ...map[string]string) map[string]string {
	labels := map[string]string{}
	for _, m := range ms {
		for k, v := range m {
			labels[k] = v
		}
	}

	return labels
}

func uniqueStrings(input []string) []string {
	seen := make(map[string]bool)
	result := []string{}

	for _, v := range input {
		if !seen[v] {
			seen[v] = true
			result = append(result, v)
		}
	}
	return result
}

func (mrs *MonitoringRuleSet) createBaseRuleLabels(w string) map[string]string {
	return map[string]string{
		"namespace": mrs.Slo.Namespace,
		"service":   mrs.Slo.Spec.Service,
		"sli_name":  mrs.Sli.Name,
		"slo_name":  mrs.Slo.Name,
		"window":    w,
	}
}

func (mrs *MonitoringRuleSet) createUserDefinedRuleLabels() map[string]string {
	relevantLabels := make(map[string]string)
	labelPrefix := "label.osko.dev/"
	for key, value := range mrs.Slo.ObjectMeta.Labels {
		if strings.HasPrefix(key, labelPrefix) {
			relevantKey := strings.TrimPrefix(key, labelPrefix)
			relevantLabels[relevantKey] = value
		}
	}

	return relevantLabels
}

// groupByLabels returns the label names the SLI should be aggregated by, as
// configured via the osko.dev/groupBy annotation. An empty result means the
// recording rules collapse to a single series, which is what makes stamping
// the rule labels safe.
func (mrs *MonitoringRuleSet) groupByLabels() []string {
	raw := mrs.Slo.ObjectMeta.Annotations[annotationGroupBy]
	if raw == "" {
		return nil
	}

	parts := strings.Split(raw, ",")
	labels := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		labels = append(labels, trimmed)
	}

	return uniqueStrings(labels)
}

// groupingClause renders the PromQL `by (...)` suffix, or an empty string when
// no grouping is configured.
func (mrs *MonitoringRuleSet) groupingClause() string {
	labels := mrs.groupByLabels()
	if len(labels) == 0 {
		return ""
	}
	return fmt.Sprintf(" by (%s)", strings.Join(labels, ", "))
}

// ruleLabels builds the label set stamped onto every generated rule. Labels
// carried by the data itself (the groupBy set) are deliberately excluded so the
// rule labels never overwrite them.
func (mrs *MonitoringRuleSet) ruleLabels(w string) map[string]string {
	labels := mergeLabels(mrs.createBaseRuleLabels(w), mrs.createUserDefinedRuleLabels())
	for _, groupBy := range mrs.groupByLabels() {
		delete(labels, groupBy)
	}
	return labels
}

// alertLabels stamps the SLO's context onto a burn-rate alert, matching what
// recording rules already carry, so a receiver can attribute the page.
//
// window is dropped because an alert spans two windows, which short_window and
// long_window describe. The five alert-specific keys are applied last so an
// osko.dev/groupBy naming one of them cannot drop it: routing and inhibit_rules
// key on slo_name.
func (mrs *MonitoringRuleSet) alertLabels(severity, shortWindow, longWindow string) map[string]string {
	labels := mrs.ruleLabels(shortWindow)
	delete(labels, "window")

	return mergeLabels(labels, map[string]string{
		"severity":     severity,
		"slo_name":     mrs.Slo.Name,
		"sli_name":     mrs.Sli.Name,
		"short_window": shortWindow,
		"long_window":  longWindow,
	})
}

// selectorFor renders a PromQL label selector body pinned to a single window.
func (mrs *MonitoringRuleSet) selectorFor(w string) string {
	return mapToColonSeparatedString(mrs.ruleLabels(w))
}

func (mrs *MonitoringRuleSet) aggregation() string {
	if mrs.Sli.Spec.RatioMetric.Counter {
		return counterAggregation
	}
	return gaugeAggregation
}

// rangeExpr renders `sum(<agg>(<query>[<window>]))[ by (...)]`.
func (mrs *MonitoringRuleSet) rangeExpr(query, w string) string {
	return fmt.Sprintf("sum(%s(%s[%s]))%s", mrs.aggregation(), query, w, mrs.groupingClause())
}

func (mrs *MonitoringRuleSet) totalExpr(w string) string {
	return mrs.rangeExpr(mrs.Sli.Spec.RatioMetric.Total.MetricSource.Spec.Query, w)
}

// goodExpr renders the numerator of the SLI ratio. When only a bad metric is
// configured the good series is inlined as `total - bad` so no intermediate
// recording rule (and therefore no selector-less duplicate labelset) is needed.
func (mrs *MonitoringRuleSet) goodExpr(w string) string {
	if query := mrs.Sli.Spec.RatioMetric.Good.MetricSource.Spec.Query; query != "" {
		return mrs.rangeExpr(query, w)
	}

	return fmt.Sprintf(
		"(%s - %s)",
		mrs.totalExpr(w),
		mrs.rangeExpr(mrs.Sli.Spec.RatioMetric.Bad.MetricSource.Spec.Query, w),
	)
}

func (mrs *MonitoringRuleSet) createTargetRule(reportingWindow string) monitoringv1.Rule {
	return monitoringv1.Rule{
		Record: fmt.Sprintf("%s_slo_target", RecordPrefix),
		Expr:   intstr.FromString(fmt.Sprintf("vector(%s)", mrs.Slo.Spec.Objectives[0].Target)),
		Labels: mrs.ruleLabels(reportingWindow),
	}
}

func (mrs *MonitoringRuleSet) createSliTotalRule(w string) monitoringv1.Rule {
	return monitoringv1.Rule{
		Record: fmt.Sprintf("%s_sli_total", RecordPrefix),
		Expr:   intstr.FromString(mrs.totalExpr(w)),
		Labels: mrs.ruleLabels(w),
	}
}

// The base window total is already a per-second rate (or gauge average), so
// avg_over_time preserves its units; sum_over_time would scale it by the sample
// count and is wrong here.
func (mrs *MonitoringRuleSet) createDerivedSliTotalRule(w, baseWindow string) monitoringv1.Rule {
	return monitoringv1.Rule{
		Record: fmt.Sprintf("%s_sli_total", RecordPrefix),
		Expr: intstr.FromString(fmt.Sprintf(
			"avg_over_time(%s_sli_total{%s}[%s])",
			RecordPrefix,
			mrs.selectorFor(baseWindow),
			w,
		)),
		Labels: mrs.ruleLabels(w),
	}
}

func (mrs *MonitoringRuleSet) createRawSliMeasurementRule(w string) monitoringv1.Rule {
	return monitoringv1.Rule{
		Record: fmt.Sprintf("%s_sli_measurement", RecordPrefix),
		Expr: intstr.FromString(fmt.Sprintf(
			"clamp_min(clamp_max(%s / %s, 1), 0)",
			mrs.goodExpr(w),
			mrs.totalExpr(w),
		)),
		Labels: mrs.ruleLabels(w),
	}
}

func (mrs *MonitoringRuleSet) createDerivedSliMeasurementRule(w, baseWindow string) monitoringv1.Rule {
	return monitoringv1.Rule{
		Record: fmt.Sprintf("%s_sli_measurement", RecordPrefix),
		Expr: intstr.FromString(fmt.Sprintf(
			"clamp_min(clamp_max(avg_over_time(%s_sli_measurement{%s}[%s]), 1), 0)",
			RecordPrefix,
			mrs.selectorFor(baseWindow),
			w,
		)),
		Labels: mrs.ruleLabels(w),
	}
}

func (mrs *MonitoringRuleSet) createBurnRateRule(w string, errorBudgetTarget float64) monitoringv1.Rule {
	return monitoringv1.Rule{
		Record: fmt.Sprintf("%s_error_budget_burn_rate", RecordPrefix),
		Expr: intstr.FromString(fmt.Sprintf(
			"(1 - %s_sli_measurement{%s}) / %.10f",
			RecordPrefix,
			mrs.selectorFor(w),
			errorBudgetTarget,
		)),
		Labels: mrs.ruleLabels(w),
	}
}

func (mrs *MonitoringRuleSet) isPrometheusSource() bool {
	sourceString := ""
	opts := []string{mrs.Sli.Spec.RatioMetric.Total.MetricSource.Type, mrs.Sli.Spec.ThresholdMetric.MetricSource.Type}
	for _, opt := range opts {
		if opt != "" {
			sourceString = opt
			break
		}
	}
	sourceString = strings.ToLower(sourceString)
	switch sourceString {
	case
		"prometheus",
		"mimir",
		"cortex",
		"victoriametrics",
		"thanos":
		return true
	}
	return false
}

func parseTarget(target string) (float64, error) {
	return strconv.ParseFloat(target, 64)
}

func validateTarget(target float64) error {
	if target >= 1.0 {
		return fmt.Errorf("SLO target must be less than 1.0 (100%%), got %.4f: %w", target, errors.ErrInvalidTarget)
	}
	if target <= 0 {
		return fmt.Errorf("SLO target must be greater than 0, got %.4f: %w", target, errors.ErrInvalidTarget)
	}
	return nil
}

// validateSpec rejects SLO/SLI combinations that would otherwise generate
// syntactically invalid or silently wrong PromQL. These messages surface on the
// SLO status, so they name both the offending value and the fix.
func (mrs *MonitoringRuleSet) validateSpec() error {
	budgetingMethod := mrs.Slo.Spec.BudgetingMethod
	if budgetingMethod != "" && budgetingMethod != budgetingMethodOccurrences {
		return fmt.Errorf(
			"budgetingMethod %q is not implemented, only %q is currently supported: %w",
			budgetingMethod, budgetingMethodOccurrences, errors.ErrUnsupportedBudgetingMethod,
		)
	}

	totalQuery := mrs.Sli.Spec.RatioMetric.Total.MetricSource.Spec.Query

	if mrs.Sli.Spec.ThresholdMetric.MetricSource.Type != "" && totalQuery == "" {
		return fmt.Errorf(
			"thresholdMetric SLIs are not yet supported, please express the SLI as a ratioMetric with total and good (or bad) queries: %w",
			errors.ErrInvalidSLIConfiguration,
		)
	}

	if totalQuery == "" {
		return fmt.Errorf(
			"a ratioMetric.total.metricSource.spec.query is required to generate SLO rules: %w",
			errors.ErrInvalidSLIConfiguration,
		)
	}

	if mrs.Sli.Spec.RatioMetric.Good.MetricSource.Spec.Query == "" &&
		mrs.Sli.Spec.RatioMetric.Bad.MetricSource.Spec.Query == "" {
		return fmt.Errorf(
			"one of ratioMetric.good.metricSource.spec.query or ratioMetric.bad.metricSource.spec.query is required to generate SLO rules: %w",
			errors.ErrInvalidSLIConfiguration,
		)
	}

	return nil
}

// longWindowStrategy resolves the osko.dev/longWindowStrategy annotation.
// Anything other than an explicit "raw" falls back to the derived default.
func (mrs *MonitoringRuleSet) longWindowStrategy() string {
	log := ctrllog.FromContext(context.Background())

	switch value := mrs.Slo.ObjectMeta.Annotations[annotationLongWindowStrategy]; value {
	case "", longWindowStrategyDerived:
		return longWindowStrategyDerived
	case longWindowStrategyRaw:
		return longWindowStrategyRaw
	default:
		log.V(1).Info("Unknown long window strategy, falling back to derived",
			"annotation", annotationLongWindowStrategy,
			"value", value,
			"slo", mrs.Slo.Name)
		return longWindowStrategyDerived
	}
}

// resolveWindows builds the deterministic, ascending set of windows the SLO
// records rules for: the base window, the reporting window and every alerting
// window.
func resolveWindows(baseWindow, reportingWindow string) ([]window, error) {
	names := append([]string{baseWindow, reportingWindow}, alertingWindows...)
	names = uniqueStrings(names)

	windows := make([]window, 0, len(names))
	for _, name := range names {
		duration, err := model.ParseDuration(name)
		if err != nil {
			return nil, fmt.Errorf("failed to parse window %q: %w", name, errors.ErrInvalidWindow)
		}
		windows = append(windows, window{name: name, duration: duration})
	}

	sort.Slice(windows, func(i, j int) bool {
		if windows[i].duration != windows[j].duration {
			return windows[i].duration < windows[j].duration
		}
		return windows[i].name < windows[j].name
	})

	return windows, nil
}

func (mrs *MonitoringRuleSet) SetupRules() ([]monitoringv1.RuleGroup, error) {
	log := ctrllog.FromContext(context.Background())

	if err := mrs.validateSpec(); err != nil {
		return nil, err
	}

	if !mrs.isPrometheusSource() {
		return []monitoringv1.RuleGroup{}, fmt.Errorf("unsupported metric source type")
	}

	baseWindow := mrs.BaseWindow
	reportingWindow := defaultReportingWindow
	if len(mrs.Slo.Spec.TimeWindow) > 0 && mrs.Slo.Spec.TimeWindow[0].Duration != "" {
		reportingWindow = string(mrs.Slo.Spec.TimeWindow[0].Duration)
	}
	log.V(1).Info("Starting SetupRules", "baseWindow", baseWindow, "reportingWindow", reportingWindow)

	target, err := parseTarget(mrs.Slo.Spec.Objectives[0].Target)
	if err != nil {
		return nil, fmt.Errorf("failed to parse SLO target: %w", err)
	}

	if err := validateTarget(target); err != nil {
		return nil, err
	}

	errorBudgetTarget := 1.0 - target
	log.V(1).Info("SLO configuration", "target", target, "errorBudgetTarget", errorBudgetTarget)

	windows, err := resolveWindows(baseWindow, reportingWindow)
	if err != nil {
		return nil, err
	}

	baseDuration, err := model.ParseDuration(baseWindow)
	if err != nil {
		return nil, fmt.Errorf("failed to parse base window %q: %w", baseWindow, errors.ErrInvalidWindow)
	}

	reportingDuration, err := model.ParseDuration(reportingWindow)
	if err != nil {
		return nil, fmt.Errorf("failed to parse reporting window %q: %w", reportingWindow, errors.ErrInvalidWindow)
	}

	// A derived window must never depend on a base window that is itself
	// longer than the raw threshold, otherwise the base measurement would be
	// derived from itself.
	forceRaw := mrs.longWindowStrategy() == longWindowStrategyRaw || baseDuration > maxRawWindow
	isDerived := func(d model.Duration) bool { return !forceRaw && d > maxRawWindow }

	// Rules are emitted in strict dependency order inside a single group so
	// Prometheus resolves the whole chain within one evaluation interval.
	recordingRules := []monitoringv1.Rule{
		mrs.createTargetRule(reportingWindow),
		mrs.createSliTotalRule(baseWindow),
	}

	// Dashboards select osko_sli_total by the reporting window, so it is
	// recorded for that window too unless it is already the base window.
	if reportingWindow != baseWindow {
		if isDerived(reportingDuration) {
			recordingRules = append(recordingRules, mrs.createDerivedSliTotalRule(reportingWindow, baseWindow))
		} else {
			recordingRules = append(recordingRules, mrs.createSliTotalRule(reportingWindow))
		}
	}

	var derivedMeasurements []monitoringv1.Rule
	for _, w := range windows {
		if isDerived(w.duration) {
			derivedMeasurements = append(derivedMeasurements, mrs.createDerivedSliMeasurementRule(w.name, baseWindow))
			continue
		}
		recordingRules = append(recordingRules, mrs.createRawSliMeasurementRule(w.name))
	}
	recordingRules = append(recordingRules, derivedMeasurements...)

	burnRates := make([]monitoringv1.Rule, 0, len(windows))
	for _, w := range windows {
		burnRates = append(burnRates, mrs.createBurnRateRule(w.name, errorBudgetTarget))
	}

	sloName := mrs.Slo.Name
	magicAlerting := mrs.Slo.ObjectMeta.Annotations[annotationMagicAlerting] == "true"
	log.V(1).Info("Magic alerting", "SLO", sloName, "enabled", magicAlerting)

	// Burn rates ship with the alerts consuming them, not the measurements they
	// derive from. Either layout costs one evaluation interval from measurement
	// to alert, but this one splits 2*len(windows) rules over two groups rather
	// than stacking them in one, staying clear of Mimir's default 20-rule
	// ruler_max_rules_per_rule_group limit.
	if !magicAlerting {
		recordingRules = append(recordingRules, burnRates...)
		return []monitoringv1.RuleGroup{
			{Name: fmt.Sprintf("%s_recording", sloName), Rules: recordingRules},
		}, nil
	}

	return []monitoringv1.RuleGroup{
		{Name: fmt.Sprintf("%s_recording", sloName), Rules: recordingRules},
		{Name: fmt.Sprintf("%s_alert", sloName), Rules: append(burnRates, mrs.buildAlertRules(burnRates)...)},
	}, nil
}

// alertTier is one row of the SRE Workbook's multiwindow, multi-burn-rate table.
// https://sre.google/workbook/alerting-on-slos/#6-multiwindow-multi-burn-rate-alerts
//
// Both windows in a tier compare against the same burnRate: the rate belongs to
// the tier, not to a window. wait is the alert's `for`, kept short on the page
// tiers because the 1h/5m tier targets a ~2 minute detection time.
type alertTier struct {
	short    string
	long     string
	severity config.SREAlertSeverity
	burnRate float64
	wait     monitoringv1.Duration
}

// alertTiers is a function rather than a package-level var because the burn rates
// come from config.Cfg, which NewConfig() populates after package initialisation.
// A var would capture zeroes, and every alert would compare against `> 0.0`.
func alertTiers() []alertTier {
	rates := config.Cfg.AlertingBurnRates
	return []alertTier{
		{short: "5m", long: "1h", severity: config.PageCritical, burnRate: rates.PageCriticalBurnRate, wait: "2m"},
		{short: "30m", long: "6h", severity: config.PageHigh, burnRate: rates.PageHighBurnRate, wait: "2m"},
		{short: "2h", long: "24h", severity: config.TicketHigh, burnRate: rates.TicketHighBurnRate, wait: "15m"},
		{short: "6h", long: "3d", severity: config.TicketMedium, burnRate: rates.TicketMediumBurnRate, wait: "15m"},
	}
}

func (mrs *MonitoringRuleSet) buildAlertRules(alertingBurnRates []monitoringv1.Rule) []monitoringv1.Rule {
	burnRateWindows := mrs.getBurnRateWindows(alertingBurnRates)

	var alertRules []monitoringv1.Rule
	for _, tier := range alertTiers() {
		if !burnRateWindows.hasWindows(tier.short, tier.long) {
			continue
		}
		alertRules = append(alertRules, mrs.createMultiBurnRateAlert(burnRateWindows, tier))
	}

	return alertRules
}

type burnRateWindows struct {
	windows map[string]monitoringv1.Rule
}

func (brw *burnRateWindows) hasWindows(required ...string) bool {
	for _, w := range required {
		if _, exists := brw.windows[w]; !exists {
			return false
		}
	}
	return true
}

func (brw *burnRateWindows) get(w string) monitoringv1.Rule {
	return brw.windows[w]
}

func (mrs *MonitoringRuleSet) getBurnRateWindows(burnRates []monitoringv1.Rule) *burnRateWindows {
	windows := make(map[string]monitoringv1.Rule)
	for _, br := range burnRates {
		if w, ok := br.Labels["window"]; ok && w != "" {
			windows[w] = br
		}
	}
	return &burnRateWindows{windows: windows}
}

func isValidRule(rule monitoringv1.Rule) bool {
	return rule.Record != "" && rule.Expr.String() != ""
}

func (mrs *MonitoringRuleSet) createMultiBurnRateAlert(
	brw *burnRateWindows,
	tier alertTier,
) monitoringv1.Rule {
	log := ctrllog.FromContext(context.Background())

	shortWindow := brw.get(tier.short)
	longWindow := brw.get(tier.long)

	if !isValidRule(shortWindow) || !isValidRule(longWindow) {
		log.V(1).Info("Missing or invalid burn rate windows for alert",
			"severity", tier.severity,
			"shortWindowValid", isValidRule(shortWindow),
			"longWindowValid", isValidRule(longWindow))
		return monitoringv1.Rule{}
	}

	shortLabels := mapToColonSeparatedString(shortWindow.Labels)
	longLabels := mapToColonSeparatedString(longWindow.Labels)

	// ignoring(window) is load-bearing: `and` matches on the full label set, and
	// the two sides differ in `window`, so a plain conjunction never intersects
	// and the alert can never fire.
	alertExpression := fmt.Sprintf(
		"(%s{%s} > %.1f and ignoring(window) %s{%s} > %.1f)",
		shortWindow.Record, shortLabels, tier.burnRate,
		longWindow.Record, longLabels, tier.burnRate,
	)

	alertingTool := mrs.Slo.ObjectMeta.Annotations[annotationAlertingTool]
	if alertingTool == "" {
		alertingTool = config.Cfg.AlertingTool
	}

	severities := config.AlertSeveritiesByTool(alertingTool)
	toolSeverity := severities.GetSeverity(tier.severity)

	log.V(1).Info("Alerting rule", "sreSeverity", tier.severity, "toolSeverity", toolSeverity)

	wait := tier.wait

	return monitoringv1.Rule{
		Alert:  fmt.Sprintf("%s_alert_%s", mrs.Slo.Name, tier.severity),
		Expr:   intstr.FromString(alertExpression),
		For:    &wait,
		Labels: mrs.alertLabels(toolSeverity, shortWindow.Labels["window"], longWindow.Labels["window"]),
		Annotations: map[string]string{
			"summary":     "SLO Burn Rate Alert",
			"description": fmt.Sprintf("The burn rate of SLO %s is consuming error budget faster than acceptable. Short window: %s, Long window: %s", mrs.Slo.Name, shortWindow.Labels["window"], longWindow.Labels["window"]),
		},
	}
}

func CreatePrometheusRule(slo *openslov1.SLO, sli *openslov1.SLI) (*monitoringv1.PrometheusRule, error) {
	baseWindow := model.Duration(config.Cfg.DefaultBaseWindow).String()
	if slo.ObjectMeta.Annotations[annotationBaseWindow] != "" {
		baseWindow = slo.ObjectMeta.Annotations[annotationBaseWindow]
	}

	mrs := &MonitoringRuleSet{
		Slo:        slo,
		Sli:        sli,
		BaseWindow: baseWindow,
	}

	ruleGroups, err := mrs.SetupRules()
	if err != nil {
		return nil, err
	}

	ownerRef := []metav1.OwnerReference{
		*metav1.NewControllerRef(
			slo,
			openslov1.GroupVersion.WithKind("SLO"),
		),
	}

	objectMeta := metav1.ObjectMeta{
		Name:      slo.Name,
		Namespace: slo.Namespace,
		Labels: mergeLabels(slo.Labels, map[string]string{
			LabelManagedBy: LabelManagedByValue,
			LabelSLOName:   slo.Name,
		}),
		Annotations:     slo.Annotations,
		OwnerReferences: ownerRef,
	}

	typeMeta := metav1.TypeMeta{
		APIVersion: "monitoring.coreos.com/v1",
		Kind:       "PrometheusRule",
	}

	prometheusRule := monitoringv1.PrometheusRule{}

	prometheusRule.TypeMeta = typeMeta
	prometheusRule.ObjectMeta = objectMeta
	prometheusRule.Spec = monitoringv1.PrometheusRuleSpec{
		Groups: ruleGroups,
	}

	return &prometheusRule, nil
}
