# permissions for end users to view alertpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alertpolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slo-kubernetes-operator
    app.kubernetes.io/part-of: slo-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: alertpolicy-viewer-role
rules:
- apiGroups:
  - openslo.com
  resources:
  - alertpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openslo.com
  resources:
  - alertpolicies/status
  verbs:
  - get
