# permissions for end users to edit alertconditions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alertcondition-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slo-kubernetes-operator
    app.kubernetes.io/part-of: slo-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: alertcondition-editor-role
rules:
- apiGroups:
  - openslo.com
  resources:
  - alertconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.com
  resources:
  - alertconditions/status
  verbs:
  - get
