# permissions for end users to view mimirrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mimirrule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: osko
    app.kubernetes.io/part-of: osko
    app.kubernetes.io/managed-by: kustomize
  name: mimirrule-viewer-role
rules:
- apiGroups:
  - osko.dev
  resources:
  - mimirrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osko.dev
  resources:
  - mimirrules/status
  verbs:
  - get
