# permissions for end users to edit mimirrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "osko.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-mimirrule-editor-role
rules:
- apiGroups:
  - osko.dev
  resources:
  - mimirrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osko.dev
  resources:
  - mimirrules/status
  verbs:
  - get
