---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "osko.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-prometheusrule-editor-role
rules:
- apiGroups:
    - monitoring.coreos.com
  resources:
    - prometheusrules
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
