apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: osko
    app.kubernetes.io/managed-by: kustomize
  name: alertmanagerconfig-sample
type: Opaque
stringData:
    alertmanager.yaml: |-
      route:
          receiver: 'default-receiver'
      
      receivers:
        - name: 'default-receiver'
          email_configs:
            - to: 'example@domain.com'
              from: 'alertmanager@domain.com'
              smarthost: 'smtp.domain.com:587'
              auth_username: 'alertmanager'
              auth_password: 'password'
              auth_identity: 'alertmanager@domain.com'

