apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  annotations:
    osko.dev/datasourceRef: "mimir-infra-ds"
  name: alertmanagerconfig-sample
spec:
  receivers:
  - name: OpsGenie
    opsgenieConfigs:
    - apiURL: https://api.eu.opsgenie.com
  route:
    continue: true
    groupBy:
    - alertname
    - job
    - statefulset
    - daemonset
    groupInterval: 5min
    groupWait: 30s
    receiver: OpsGenie
    repeatInterval: 12h
    routes:
    - continue: true
      groupInterval: 1m
      matchers:
      - name: alertname
        value: DeadMansSwitch
      receiver: heartbeat
      repeatInterval: 1m
    - groupInterval: 1m
      matchers:
      - name: alertname
        value: DeadMansSwitch
      receiver: heartbeat_betteruptime
      repeatInterval: 1m
    - continue: true
      matchers:
      - matchType: =~
        name: alertname
        value: .*
      receiver: betteruptime
    - matchers:
      - matchType: =~
        name: alertname
        value: .*
      receiver: opsgenie
