apiVersion: openslo.com/v1
kind: AlertPolicy
metadata:
  labels:
    app.kubernetes.io/name: alertpolicy
    app.kubernetes.io/instance: alertpolicy-sample
    app.kubernetes.io/part-of: slo-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: slo-kubernetes-operator
  name: alertpolicy-sample
spec:
  description: testing AlertPolicy
  alertWhenNoData: true
  alertWhenBreaching: true
  alertWhenResolved: false
  conditions:
    - kind: AlertCondition
      spec:
        description: test description
  # notificationTargets:
  #   - kind: AlertNotificationTarget
  #     name: inline-AlertNotificationTarget
