apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
data:
  agent.river: |
    prometheus.remote_write "local" {
      endpoint {
        url = "http://mimir-service:9009/api/v1/push"
        headers = {
          "X-Scope-OrgID" = "monitoring",
        }
      }
    }
    prometheus.relabel "cluster" {
      rule {
        target_label = "cluster"
        replacement = "local"
      }
      forward_to = [
        prometheus.remote_write.local.receiver,
      ]
    }
    prometheus.scrape "static" {
      forward_to = [
        prometheus.relabel.cluster.receiver,
      ]
      targets = [
        {
          "__address__" = "mimir-service:9009",
        },
      ]
    }
