apiVersion: openslo.com/v1
kind: SLO
metadata:
  name: kubelet-pod-start-latency
  namespace: monitoring
  labels:
    label.osko.dev/domain: infrastructure
    label.osko.dev/service: kubelet
    label.osko.dev/system: kubernetes
    label.osko.dev/team: platform
  annotations:
    osko.dev/datasourceRef: mimir-infra-ds
    osko.dev/magicAlerting: "true"
spec:
  service: kubelet
  description: "Pods should start within 30 seconds"
  budgetingMethod: Occurrences
  indicator:
    metadata:
      name: kubelet-pod-start-latency
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            metricSourceRef: mimir-infra-ds
            type: Mimir
            spec:
              query: "kubelet_pod_start_duration_seconds_bucket{le=\"30\"}"
        total:
          metricSource:
            metricSourceRef: mimir-infra-ds
            type: Mimir
            spec:
              query: "kubelet_pod_start_duration_seconds_count"
  objectives:
    - target: "0.99"
      displayName: "99% Pods Start Under 30s"
  timeWindow:
    - duration: 28d
      isRolling: true
