{
 "title": "OSKO / SLOs",
 "description": "Look at specific SLOs",
 "tags": [ "osko" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": "prometheus" },
   {
    "name": "window",
    "label": "Window",
    "query": "label_values(osko_sli_measurement, window)"
   },
   {
    "name": "team",
    "label": "Team",
    "query": "label_values(osko_slo_target, team)"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values(osko_slo_target{team=~\"$team\"}, domain)"
   },
   {
    "name": "system",
    "label": "System",
    "query": "label_values(osko_slo_target{team=~\"$team\", domain=~\"$domain\"}, system)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(osko_slo_target{team=~\"$team\", domain=~\"$domain\", system=~\"$system\"}, service)"
   },
   {
    "name": "slo",
    "label": "SLO",
    "query": "label_values(osko_slo_target{team=~\"$team\", domain=~\"$domain\", system=~\"$system\", service=~\"$service\"}, slo_name)"
   }
  ]
 },
 "panels": [
  { "title": "$slo SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "slo" },
  {
   "title": "Passing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    osko_sli_measurement{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"}\n) by (slo_name)\n> bool\nsum(\n    osko_slo_target{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"}\n) by (slo_name)\n"
    }
   ]
  },
  {
   "title": "SLI vs SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(\n    osko_sli_measurement{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"}\n) by (slo_name)\n",
     "legendFormat": "Measurement"
    },
    {
     "expr": "min(\n    osko_slo_target{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"}\n) by (slo_name)\n",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Error Budget burn rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(\n    osko_error_budget_burn_rate{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"}\n) by (slo_name)\n",
     "legendFormat": "Burn rate {{ window }}"
    },
    { "expr": "vector(1)\n", "legendFormat": "Threshold {{ window }}" }
   ]
  },
  {
   "title": "Total events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(osko_sli_total{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"})\n"
    }
   ]
  },
  {
   "title": "Errors budget",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    osko_sli_total{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"}\n    * on(slo_name, service, namespace) group_left()\n    (1 - osko_slo_target{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\"})\n)\n",
     "legendFormat": "Budget"
    }
   ]
  },
  {
   "title": "Errors remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    clamp_min(\n        osko_sli_measurement{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"}\n        - on(slo_name, service, namespace) group_left()\n        osko_slo_target{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\"},\n    0) * on(slo_name, service, namespace, window)\n    osko_sli_total{domain=~\"$domain\", system=~\"$system\", team=~\"$team\", service=~\"$service\", slo_name=~\"$slo\", window=\"$window\"}\n)\n",
     "legendFormat": "Remaining"
    }
   ]
  }
 ]
}